name: widget
version: 0.2.7-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/dart-lang/widget.dart
environment:
  sdk: '>=0.6.15'
dependencies:
  bot: '>=0.23.0'
  bot_web: '>=0.20.4'
  html5lib: '>=0.4.4'
  meta: '>=0.6.15'
  web_ui: '>=0.4.17+3'
dev_dependencies:
  bot_test: any
  hop: '>=0.24.1+1'
  unittest: '>=0.6.15'
