name: widget
version: 0.2.4
author: Kevin Moore <kevin@thinkpixellab.com>
description: A set of reusable Web Components for Dart applications
homepage: https://github.com/kevmoo/widget.dart
environment:
  sdk: '>=0.4.4+4.r20810'
dependencies:
  html5lib: '>=0.4.1'
  bot: '>=0.16.2'
  web_ui: '>=0.4.4'
  meta: '>=0.4.4+4'
dev_dependencies:
  unittest: '>=0.4.4+4'
